branches:
  only:
  - source

sudo: required

services:
  - docker

before_install:
  - rm -rf public || exit 0

script:
  - make generate-using-docker

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  keep-history: true
  verbose: true
  on:
    branch: source
