branches:
  only:
  - source

sudo: required

services:
  - docker

script:
  - rm -rf public || exit 0
  - git clone -b master https://$GITHUB_TOKEN@github.com/Gonzih/gonzih.github.com.git public
  - make generate-using-docker
  - make deploy
