branches:
  only:
  - source

sudo: required

services:
  - docker

before_install:
  - rm -rf public || exit 0
  - git clone -b master https://$GITHUB_TOKEN@github.com/Gonzih/gonzih.github.com.git public
  - rm -rf public/.git

script:
  - make generate-using-docker

deploy:
  - make deploy
